apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
      - args:
        - serve
        - --env
        - production
        - --hostname
        - 0.0.0.0
        - --port
        - "8080"
        env:
        - name: DATABASE_HOST
          value: db
        - name: DATABASE_NAME
          value: vapor_database
        - name: DATABASE_PASSWORD
          value: vapor_password
        - name: DATABASE_USERNAME
          value: vapor_username
        - name: LOG_LEVEL
          value: debug
        image: danielmandea/aotsmoothie-web:1
        imagePullPolicy: ""
        name: app
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
