apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: revert
  name: revert
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: revert
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: revert
    spec:
      containers:
      - args:
        - migrate
        - --revert
        - --yes
        env:
        - name: DATABASE_HOST
          value: db
        - name: DATABASE_NAME
          value: vapor_database
        - name: DATABASE_PASSWORD
          value: vapor_password
        - name: DATABASE_USERNAME
          value: vapor_username
        - name: LOG_LEVEL
          value: debug
        image: aotsmoothieweb:latest
        imagePullPolicy: ""
        name: revert
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
